"""
AI automation package
"""

from .automation import AutomationEngine
from .frequency_lock import FrequencyLockController
from .chaimera3sp import (
    CHAiMERAProvider,
    CHAiMERA3sp,
    TraceryNode,
    SeriesPattern,
    AccuracyReport,
    DataResearchReport,
    TraceryStore,
    KnowledgeScraper,
    SeriesDecipher,
    AccuracyScrutineer,
    InferenceStreamMonitor,
)
from .tlc import (
    TLCModule,
    TechnicalObservation,
    KnowledgeEntry,
    TechnicalKnowledgeStore,
    PatternRecognizer,
    DreamStateEngine,
    DreamSession,
    DreamEvaluation,
    DreamResearch,
    DreamCorruption,
    ReactiveCapture,
    MindStatus,
    AnomalyFilter,
    AnomalyRecord,
    OutcomeInventory,
    PredictiveReasoner,
    Prediction,
    AutonomousDecision,
    # Voice analysis
    VoiceFrame,
    PitchContour,
    SentencePattern,
    EmotionalState,
    CortexCouncilRecommendation,
    CompassionResponse,
    CompassionInventory,
    VoiceAnalysisEngine,
    TWINBRAiN,
    # Voice emotion constants
    EMOTION_CALM,
    EMOTION_EXCITED,
    EMOTION_DISTRESSED,
    EMOTION_UNCERTAIN,
    EMOTION_ASSERTIVE,
)

__all__ = [
    "AutomationEngine",
    "FrequencyLockController",
    "CHAiMERA3sp",
    "CHAiMERAProvider",
    "TraceryNode",
    "SeriesPattern",
    "AccuracyReport",
    "DataResearchReport",
    "TraceryStore",
    "KnowledgeScraper",
    "SeriesDecipher",
    "AccuracyScrutineer",
    "InferenceStreamMonitor",
    "TLCModule",
    "TechnicalObservation",
    "KnowledgeEntry",
    "TechnicalKnowledgeStore",
    "PatternRecognizer",
    "DreamStateEngine",
    "DreamSession",
    "DreamEvaluation",
    "DreamResearch",
    "DreamCorruption",
    "ReactiveCapture",
    "MindStatus",
    "AnomalyFilter",
    "AnomalyRecord",
    "OutcomeInventory",
    "PredictiveReasoner",
    "Prediction",
    "AutonomousDecision",
    # Voice analysis
    "VoiceFrame",
    "PitchContour",
    "SentencePattern",
    "EmotionalState",
    "CortexCouncilRecommendation",
    "CompassionResponse",
    "CompassionInventory",
    "VoiceAnalysisEngine",
    "TWINBRAiN",
    "EMOTION_CALM",
    "EMOTION_EXCITED",
    "EMOTION_DISTRESSED",
    "EMOTION_UNCERTAIN",
    "EMOTION_ASSERTIVE",
]

